language: node_js
node_js:
  - "5.6"
cache:
  directories:
    - node_modules
    - .nvm
env:
  - TEST_DATABASE_URL=postgres://postgres@localhost:5432/opentrials_api_test
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database opentrials_api_test;' -U postgres
script: npm run coveralls

before_deploy:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t opentrials/api:$TRAVIS_COMMIT .
deploy:
  provider: script
  script: docker push opentrials/api
  on:
    condition: "$TRAVIS_PULL_REQUEST == false"
    branch: master
