language: node_js
node_js:
  - "5.8"
cache:
  directories:
    - node_modules
    - .nvm
env:
  global:
    - TEST_DATABASE_URL=postgres://postgres@localhost:5432/opentrials_api_test

addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database opentrials_api_test;' -U postgres
script: npm run coveralls
