version: '2'
services:
  db:
    image: postgres:9.5
  elasticsearch:
    image: elasticsearch:2.2
  web:
    build: .
    command: npm start
    ports:
      - "10010:80"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
