swagger: "2.0"
info:
  version: "0.0.1"
  title: OpenTrials API
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /swagger.yaml:
    x-swagger-pipe: swagger_raw
  /trials:
    x-swagger-router-controller: trials
    get:
      tags:
        - trials
      description: Returns list of trials
      # used as the method name of the controller
      operationId: list
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/TrialsList"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /trials/{id}:
    x-swagger-router-controller: trials
    get:
      tags:
        - trials
      description: Returns list of trials
      # used as the method name of the controller
      operationId: get
      parameters:
        - name: id
          in: path
          description: ID of the trial
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/Trial"
        # responses may fall through to errors
        "404":
          description: Trial not found
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  Trial:
    required:
      - id
      - public_title
      - brief_summary
      - registration_date
      - locations
      - interventions
      - persons
    properties:
      id:
        type: string
      public_title:
        type: string
      brief_summary:
        type: string
      registration_date:
        type: string
        format: date-time
      locations:
        type: array
        items:
          $ref: '#/definitions/TrialLocation'
      interventions:
        type: array
        items:
          $ref: '#/definitions/TrialIntervention'
      persons:
        type: array
        items:
          $ref: '#/definitions/TrialPerson'
  TrialsList:
    type: array
    items:
      $ref: '#/definitions/Trial'

  TrialLocation:
    required:
      - attributes
    properties:
      role:
        enum:
          - recruitment_countries
          - other
          - null
      attributes:
        $ref: '#/definitions/Location'
  Location:
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      type:
        enum:
          - country
          - city
          - other
          - null

  TrialIntervention:
    required:
      - attributes
    properties:
      role:
        enum:
          - other
          - null
      attributes:
        $ref: '#/definitions/Intervention'
  Intervention:
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      type:
        enum:
          - drug
          - other
          - null

  TrialPerson:
    required:
      - attributes
    properties:
      role:
        enum:
          - principal_investigator
          - public_queries
          - scientific_queries
          - other
          - null
      attributes:
        $ref: '#/definitions/Person'
  Person:
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      type:
        enum:
          - other
          - null

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
