web:
  image: opentrials/api:staging
  command: bash -c "./tools/wait-for-it.sh db:5432 && ./tools/wait-for-it.sh elasticsearch:9200 && npm start"
  ports:
    - "10010:80"
  environment:
    DATABASE_URL:
    ELASTICSEARCH_URL:
  restart: always
  links:
    - db
    - elasticsearch

db:
  image: postgres:9.5
  restart: always

elasticsearch:
  image: elasticsearch:2.2
  restart: always
